rewriteBase: /hubleto-dev/
rootUrl: http://localhost/hubleto-dev
srcUrl: http://localhost/hubleto-dev/vendor/hubleto/main
assetsUrl: http://localhost/hubleto-dev/assets
dbHost: localhost
dbUser: root
dbPassword: ''
dbName: hbl_dev
dbCodepage: utf8mb4
accountFullName: Hubleto Dev
adminName: Dev
adminFamilyName: Coder
adminNick: dev-coder
adminEmail: dev@example.com
adminPassword: dev
generateDemoData: true

# Uncomment following lines if you want to have full control over
# what apps will be installed. Example below installs minimal set
# of apps.
# packagesToInstall: no-package
# appsToInstall:
#   HubletoApp\Community\Settings: []
#   HubletoApp\Community\Tools: []
#   HubletoApp\Community\Desktop: []
#   HubletoApp\Community\Usage: []

# Uncomment following lines if you want to customize look & feel
# of your Hubleto
# extraConfigEnv:
#   uiTheme: green-orange
#   logoUrl: assets/custom/images/my-hubleto.png
#   welcomeSplashImageUrl: assets/custom/images/my-hubleto.png
#   availableLanguages: []
#   appTitle: My Hubleto - Fully customized Hubleto
#   sidebarGroups:
#     crm:
#       title: CRM
#       icon: fas fa-id-card-clip
#     maintenance:
#       title: Maintenance
#       icon: fas fa-cog
